POST http://localhost:3000/projects
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5hdmlkIiwiaWF0IjoxNjEyMDE0NDIyfQ.mcBRZmK58Mp9ZH0G1WNtbW3KfGAN21DySFlG9z9Biw8

{
    "userId": 1,
    "title": "New pppp1"
}

###
GET http://localhost:3000/projects

###
GET http://localhost:3000/projects/2

###
DELETE  http://localhost:3000/projects/4

###
PUT  http://localhost:3000/projects/3
Content-Type: application/json

{
    "title": "Updated project"
}


