POST http://localhost:3000/tasks
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFtaXIiLCJpYXQiOjE2MTIyNjIzOTcsImV4cCI6MTYxMjI3MzE5N30.ZhkUm9CWhHlxvD1cX0cFfKcp_By6Y4DjVODwlfqXkuw

{
    "title": "My new task"
}

###
GET http://localhost:3000/tasks?page=1&size=20
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJlemEiLCJpYXQiOjE2MTMwNjUxMDQsImV4cCI6MTYxMzA3NTkwNH0.yqn1lS5ju7zTxbXK1yFgJVFX_g7C4nMV29OmkZDEVio

###
GET http://localhost:3000/tasks/2

###
DELETE  http://localhost:3000/tasks/2

###
PUT  http://localhost:3000/tasks/3
Content-Type: application/json

{
    "title": "Updated task",
    "completed": true
}


